### ISSUE TITLE
What to do when a frame spans across pages

### ISSUE THREAD

**Issue by USK314** [jomaway/typst-gentle-clues#12]
Hello, I always enjoy using this cool package. 

As you can see in the title, when the text inside a frame becomes too long and spans across pages, the content doesn't display properly. 
What should I do in such cases?

**Comment by jomaway** [comment]
You can pass the argument `breakable:true`.

If you want that setting for all clues use 

```
show: gentle-clues.with(
    breakable: true
)
```

**Comment by USK314** [comment]
It went well! Thank you so much

**Comment by paupereira** [comment]
@jomaway , where should one use the command
```
show: gentle-clues.with(
    breakable: true
)
```

**Comment by jomaway** [comment]
It depends, you can use it at the top of your document then it will affect all clues you add. 


You can find more Infos about show rules at the official website: https://typst.app/docs/reference/styling/
