### ISSUE TITLE
predefined clue `idea` is mentioned yet undefined

### ISSUE THREAD

**Issue by raenye** [jomaway/typst-gentle-clues#13]
It's mentioned between `task` and `tip`, but is not defined in `lib/predefined.typ`.

https://github.com/jomaway/typst-gentle-clues/blob/edbe54dace92ce1717b5aea2097d09e3a0184dc8/README.md?plain=1#L30

**Comment by jomaway** [comment]
True, i thing it is still called conclusion instead of idea. Add to the list to fix Thanks.
