### ISSUE TITLE
Allow for admonition that is split over the page

### ISSUE THREAD

**Issue by Andrew-S-Rosen** [jomaway/typst-gentle-clues#19]
Right now, an admonition cannot be split over the page, which causes a lot of unused white space. It would be great to have an option to split the admonition over the page boundary.

![image](https://github.com/user-attachments/assets/252f0062-a31d-4d75-8329-d86a928146d2)

**Comment by jomaway** [comment]
There is an argument `breakable` for this use case. You need to set it to true. 

This is also possible for all clues. So you don't have to pass it to each clue separately.

**Comment by Andrew-S-Rosen** [comment]
Wonderful! Thanks for clarifying!
