### ISSUE TITLE
Setting a different font for titles

### ISSUE THREAD

**Issue by lukas-loering** [jomaway/typst-gentle-clues#24]
My document uses a sans-serif typeface for titles and a serif typeface for basically anything else. 
Can I somehow set the clues to use a specific font for titles only?

Thanks in advance!

**Comment by jomaway** [comment]
Hi thanks for reaching out. 

There isn't a global option for this yet.
As a quick workaround you can pass content as a title and set the font there. 

```
#example(title: [
  #set text(font: "Noto Serif" )
  Your title with a different font.
])[
  #lorem(20)
]
```

If you need them more often maybe a small helper function is helpful
```
#let fh(body) = {
  set text(font: "Noto Serif")
  body
}

#example(title: fh[Your title with a different font])[
  #lorem(20)
]
```

Or if you have a show rule for headings anyway. Your could just pass a heading.  But this might have some side effects depending on your setup.
```
#info(title: [===== Test])[
  #lorem(20)
]
```  

Anyway i will put this on my todo list to make this an global option in the future. But it might take a while.

**Comment by lukas-loering** [comment]
Thanks you for the reply. The heading workaround will probably be best for my use case. 
Looking forward to the global option in the future! :)

**Comment by SolidTux** [comment]
One could make a global option by utilizing state.

**Comment by jomaway** [comment]
Thanks, @SolidTux that's exactly what I had in mind. Just traveling at the moment so it will take a while until I get around to merge and publish a new version.
