### ISSUE TITLE
Render math into `title`

### ISSUE THREAD

**Issue by saccarosium** [jomaway/typst-gentle-clues#25]
Hi,
I've been loving this package but recently I've been needing to use math in the title of the clue and It simply doesn't render it.

### Code

```typst
  #example(title: "Convert $(ab union a)^*$ into an equivalent NFA")[
    #diagram(
      // Code of diagram
    )
  ]
```

### Screenshot

![image](https://github.com/user-attachments/assets/fe293db6-a709-4196-bbb9-cea48842d93d)

**Comment by jomaway** [comment]
Thanks for reaching out. Your issue is not with gentle-clues but rather that you try to pass a string as title. 

You just need to pass the title as content.

```typ
#example(title: [Convert $("ab" union a)^* $ into an equivalent NFA])[
  #lorem(20)
]
```

**Comment by saccarosium** [comment]
Ok, thank you for the response. I did try that but for some reason it didn't work. Probably I had some errors that prevent from compiling and I was simply looking at an older file.
