### ISSUE TITLE
Have an alias to a built-in clue use alternative titles

### ISSUE THREAD

**Issue by maxigaz** [jomaway/typst-gentle-clues#8]
I typically like using the keyword `note` for adminitions. By looking at `gentle-clues.typ`, I noticed that the function `#note` is actually available (once it is imported), although it's literally the same as `#info`; its title is also just `Info`, as well as its colour and icon.

I would like to have the title match the name of the function, so when `#note` is used, `Note` should be in the title.

Would you be interested in making this change? (If not, no problem, I could simply copy the function and make my own note adminition.)

**Comment by jomaway** [comment]
Hey @maxigaz I see the point in your statement. During creating this package i just added some obvious clues and the one which were useful to me. At some point i added some aliases for different clues which are kind of similar. But i agree it would make more sense to have the same title as the clue keyword. 

Not sure about how to proceed.I might just remove the aliases or make them seperate clues.

**Comment by jomaway** [comment]
Removed all aliases in v0.5.0. 
The way is to define your own if needed. Or if you think one is so important that it should be predefined just open a PR
